<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ezhixuan</groupId>
        <artifactId>XuanBlog_Backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>blog_modules</artifactId>
    <version>0.0.1-beta</version>
    <packaging>pom</packaging>

    <modules>
        <module>blog_article</module>
        <module>blog_project</module>
        <module>blog_upload</module>
        <module>blog_card</module>
        <module>blog_message</module>
    </modules>

    <properties>
        <blog.article.version>0.0.1-beta</blog.article.version>
        <blog.card.version>0.0.1-beta</blog.card.version>
        <blog.upload.version>0.0.1-beta</blog.upload.version>
        <blog.message.version>0.0.1-beta</blog.message.version>
        <blog.common.version>0.0.1-beta</blog.common.version>
        <blog.system.version>0.0.2-beta</blog.system.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
    </dependencies>


</project>
